sudo: required

services:
  - docker

env:
  global:
    - IMAGE_NAME=fabiang/liquibase
  jobs:
    - version=4.3 LIQUIBASE_URL=https://github.com/liquibase/liquibase/releases/download/v4.3.1/liquibase-4.3.1.tar.gz latest=true
    - version=3.6 LIQUIBASE_URL=https://github.com/liquibase/liquibase/releases/download/liquibase-parent-3.6.3/liquibase-3.6.3-bin.tar.gz latest=false

script:
  - docker build --pull --build-arg LIQUIBASE_URL=$LIQUIBASE_URL --tag "$IMAGE_NAME:$version" .
  - docker run --rm -it "$IMAGE_NAME:$version" liquibase --version
  - docker run --rm -it "$IMAGE_NAME:$version" bash -c "apk add --update -q file && file /usr/local/liquibase/liquibase_extra/liquibase-mssql.jar"
  - docker run --rm -it "$IMAGE_NAME:$version" bash -c "apk add --update -q file && file /usr/local/liquibase/jdbc_drivers/postgresql.jar"
  - docker run --rm -it "$IMAGE_NAME:$version" bash -c "apk add --update -q file && file /usr/local/liquibase/jdbc_drivers/mssql-jdbc.jar"
  - docker run --rm -it "$IMAGE_NAME:$version" bash -c "apk add --update -q file && file /usr/local/liquibase/jdbc_drivers/mysql.jar"
  - docker run --rm -it "$IMAGE_NAME:$version" bash -c "apk add --update -q file && file /usr/local/liquibase/jdbc_drivers/jtds.jar"
  - docker run --rm -it "$IMAGE_NAME:$version" bash -c 'o() { apk add --update -q file; type=$(file --brief --mime-type /usr/local/liquibase/liquibase_extra/liquibase-mssql.jar); if [[ "$type" == "application/zip" ]]; then return 0; else return 1; fi }; o'
  - docker run --rm -it "$IMAGE_NAME:$version" bash -c 'o() { apk add --update -q file; type=$(file --brief --mime-type /usr/local/liquibase/jdbc_drivers/postgresql.jar); if [[ "$type" == "application/java-archive" ]]; then return 0; else return 1; fi }; o'
  - docker run --rm -it "$IMAGE_NAME:$version" bash -c 'o() { apk add --update -q file; type=$(file --brief --mime-type /usr/local/liquibase/jdbc_drivers/mssql-jdbc.jar); if [[ "$type" == "application/zip" ]]; then return 0; else return 1; fi }; o'
  - docker run --rm -it "$IMAGE_NAME:$version" bash -c 'o() { apk add --update -q file; type=$(file --brief --mime-type /usr/local/liquibase/jdbc_drivers/mysql.jar); if [[ "$type" == "application/java-archive" ]]; then return 0; else return 1; fi }; o'
  - docker run --rm -it "$IMAGE_NAME:$version" bash -c 'o() { apk add --update -q file; type=$(file --brief --mime-type /usr/local/liquibase/jdbc_drivers/jtds.jar); if [[ "$type" == "application/java-archive" ]]; then return 0; else return 1; fi }; o'

deploy:
  provider: script
  script: bash docker-push
  on:
    branch: master
