sudo: required

services:
  - docker

env:
  global:
    - IMAGE_NAME=fabiang/liquibase
    - version=3.6

before_script:
  - docker pull "$IMAGE_NAME" || true

script:
  - docker build --pull --cache-from "$IMAGE_NAME" --tag "$IMAGE_NAME" .
  - docker run --rm -it "$IMAGE_NAME" liquibase --version
  - docker run --rm -it "$IMAGE_NAME" bash -c "apk add --update -q file && file /opt/liquibase_extra/liquibase-mssql.jar"
  - docker run --rm -it "$IMAGE_NAME" bash -c "apk add --update -q file && file /opt/jdbc_drivers/postgresql.jar"
  - docker run --rm -it "$IMAGE_NAME" bash -c "apk add --update -q file && file /opt/jdbc_drivers/mssql-jdbc.jar"
  - docker run --rm -it "$IMAGE_NAME" bash -c "apk add --update -q file && file /opt/jdbc_drivers/mysql.jar"
  - docker run --rm -it "$IMAGE_NAME" bash -c "apk add --update -q file && file /opt/jdbc_drivers/jtds.jar"
  - docker run --rm -it "$IMAGE_NAME" bash -c 'o() { apk add --update -q file; type=$(file --brief --mime-type /opt/liquibase_extra/liquibase-mssql.jar); if [[ "$type" == "application/zip" ]]; then return 0; else return 1; fi }; o'
  - docker run --rm -it "$IMAGE_NAME" bash -c 'o() { apk add --update -q file; type=$(file --brief --mime-type /opt/jdbc_drivers/postgresql.jar); if [[ "$type" == "application/java-archive" ]]; then return 0; else return 1; fi }; o'
  - docker run --rm -it "$IMAGE_NAME" bash -c 'o() { apk add --update -q file; type=$(file --brief --mime-type /opt/jdbc_drivers/mssql-jdbc.jar); if [[ "$type" == "application/zip" ]]; then return 0; else return 1; fi }; o'
  - docker run --rm -it "$IMAGE_NAME" bash -c 'o() { apk add --update -q file; type=$(file --brief --mime-type /opt/jdbc_drivers/mysql.jar); if [[ "$type" == "application/java-archive" ]]; then return 0; else return 1; fi }; o'
  - docker run --rm -it "$IMAGE_NAME" bash -c 'o() { apk add --update -q file; type=$(file --brief --mime-type /opt/jdbc_drivers/jtds.jar); if [[ "$type" == "application/java-archive" ]]; then return 0; else return 1; fi }; o'

after_script:
  - docker images

before_deploy:
  - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"
  - docker tag "$IMAGE_NAME" "${IMAGE_NAME}:latest"
  - docker tag "$IMAGE_NAME" "${IMAGE_NAME}:${version}"

deploy:
  provider: script
  script: docker push "${IMAGE_NAME}:latest" && docker push "${IMAGE_NAME}:${version}"
  on:
    branch: master
