#!/bin/bash

echo "$REGISTRY_PASS" | docker login -u "$REGISTRY_USER" --password-stdin
docker push "${IMAGE_NAME}:${version}"

if [ "$latest" = "true" ]; then
    docker tag "${IMAGE_NAME}:${version}" "${IMAGE_NAME}:latest"
    docker push "${IMAGE_NAME}:latest"
fi
