#!/bin/bash

echo "$REGISTRY_PASS" | docker login -u "$REGISTRY_USER" --password-stdin
docker tag "$IMAGE_NAME" "${IMAGE_NAME}:latest"
docker tag "$IMAGE_NAME" "${IMAGE_NAME}:${version}"
docker push "${IMAGE_NAME}:latest" && docker push "${IMAGE_NAME}:${version}"
