version: 2.1
orbs:
  node: circleci/node@1.1
jobs:
  docker-image:
    environment: IMAGE_NAME=fabiang/liquibase
    parameters:
      version:
        type: string
      download_url:
        type: string
      extra_args:
        type: string
      latest:
        type: boolean
      checksum_sha1:
        type: string
      show_banner:
        type: boolean
    machine: true
    steps:
      - checkout
      - run: |
          docker build --pull << parameters.extra_args >> \
            -t $IMAGE_NAME:<< parameters.version >> \
            --build-arg LIQUIBASE_URL=<< parameters.download_url >> \
            --build-arg LIQUIBASE_CHECKSUM_SHA1=<< parameters.checksum_sha1 >> \
            --build-arg MY_LIQUIBASE_SHOW_BANNER=<< parameters.show_banner >> \
            .
      - run: |
          export version=<< parameters.version >>
          export latest=<< parameters.latest >>
          bash docker-push
workflows:
  build-all:
    jobs:
      - docker-image:
          version: "4.21"
          download_url: "https://github.com/liquibase/liquibase/releases/download/v4.21.1/liquibase-4.21.1.tar.gz"
          checksum_sha1: 57078b5b2242ee6b6938b9d6204afea75e232c34
          show_banner: false
          extra_args: " -t fabiang/liquibase:latest -t fabiang/liquibase:4"
          latest: true
      - docker-image:
          version: "4.17"
          download_url: "https://github.com/liquibase/liquibase/releases/download/v4.17.2/liquibase-4.17.2.tar.gz"
          checksum_sha1: 8829fef88d890d7c77a45912dc6b81acee209c92
          show_banner: false
          extra_args: ""
          latest: false
      - docker-image:
          version: "4.12"
          download_url: "https://github.com/liquibase/liquibase/releases/download/v4.12.0/liquibase-4.12.0.tar.gz"
          checksum_sha1: 3fe547fa1b319619057f16b387613b9c61ee69da
          show_banner: false
          extra_args: ""
          latest: false
      - docker-image:
          version: "4.8"
          download_url: "https://github.com/liquibase/liquibase/releases/download/v4.8.0/liquibase-4.8.0.tar.gz"
          checksum_sha1: 7c9cc7b4bedfcd2bdc5baa5c56eae38ecba1b25e
          show_banner: true
          extra_args: ""
          latest: false
      - docker-image:
          version: "4.8"
          download_url: "https://github.com/liquibase/liquibase/releases/download/v4.8.0/liquibase-4.8.0.tar.gz"
          checksum_sha1: 7c9cc7b4bedfcd2bdc5baa5c56eae38ecba1b25e
          show_banner: true
          extra_args: ""
          latest: false
      - docker-image:
          version: "4.5"
          download_url: "https://github.com/liquibase/liquibase/releases/download/v4.5.0/liquibase-4.5.0.tar.gz"
          checksum_sha1: f7a5440c348cf87308698447691e6c30fff433de
          show_banner: true
          extra_args: ""
          latest: false
      - docker-image:
          version: "4.3"
          download_url: "https://github.com/liquibase/liquibase/releases/download/v4.3.5/liquibase-4.3.5.tar.gz"
          checksum_sha1: 6e1edd94c024c613a59246881326babd32c120a1
          show_banner: true
          extra_args: ""
          latest: false
      - docker-image:
          version: "4.1"
          download_url: "https://github.com/liquibase/liquibase/releases/download/v4.1.1/liquibase-4.1.1.tar.gz"
          checksum_sha1: a855a089b84220ebb86969c407b67abab4f66eba
          show_banner: true
          extra_args: ""
          latest: false
      - docker-image:
          version: "3.6"
          download_url: "https://github.com/liquibase/liquibase/releases/download/liquibase-parent-3.6.3/liquibase-3.6.3-bin.tar.gz"
          checksum_sha1: 32ac40e5602d2a93a44c0c67b5b55bc304624a46
          show_banner: true
          extra_args: " -t fabiang/liquibase:3"
          latest: false
