name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ["4.3", "4.1", "3.6"]
        download_url: ["https://github.com/liquibase/liquibase/releases/download/v4.3.1/liquibase-4.3.1.tar.gz", "https://github.com/liquibase/liquibase/releases/download/v4.1.1/liquibase-4.1.1.tar.gz", "https://github.com/liquibase/liquibase/releases/download/liquibase-parent-3.6.3/liquibase-3.6.3-bin.tar.gz"]
        latests: [true, false, false]

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --build-arg LIQUIBASE_URL=${{ matrix.download_url }} --tag fabiang/liquibase:${{ matrix.version }}
